A* Pathfinding Implementation
TheBenKnee/CS-472-Senior-Design-Project pull request #70
Opened 2023-03-27 06:17 UTC by TryHardAsianNerd

Updated PathFinding class
-Uses A* algorithm to find and return shortest path to target tile.

Updated BaseTile class
-Added variables to calculate fCost, gCost, and hCost.
-Added a neighbors list to keep track of tiles.

2023-03-27 23:40 UTC, TheBenKnee requested changes

2023-03-27 23:40 UTC, TheBenKnee commented on Assets/Scripts/TileMapDemoScripts/BaseTile.cs
> +    public List<BaseTile> neighbors = new List<BaseTile>();
These variables aren't used anywhere. Is that intentional?

2023-03-27 23:40 UTC, TheBenKnee commented on Assets/Scripts/TileMapDemoScripts/BaseTile.cs
> +        x = 0; y = 0;
This entire section is copy and pasted from some below code. 

A) A bracket is left out which is causing a compilation error.
B) Like in C++, in C# you can't declare functions with the same parameters multiple times so this still wouldn't compile.

2023-03-27 23:40 UTC, TheBenKnee commented on Assets/Scripts/TileMapDemoScripts/BaseTile.cs
> +        Debug.Log("X: " + x + " Y: " + y + " Collision: " + isCollision);
When possible, try and remove Debugs from code prior to a Pull Request. They can clutter up the console and don't provide any user-facing functionality.

2023-03-27 23:40 UTC, TheBenKnee commented on Assets/Scripts/TileMapDemoScripts/BaseTile.cs
> +        this.x = x; this.y = y;
This is already done two lines up, is this intentional?

2023-03-27 23:40 UTC, TheBenKnee commented on Assets/Scripts/TileMapDemoScripts/MapManager.cs
> -        player.updateLocation(10.0f * Time.deltaTime);
This breaks the intended functionality of the method. With the player's location not being updated, they can't be moved towards the pathfinded location. Did you intend to move this movement logic to its own method?

2023-03-28 00:33 UTC, VinceMack commented
This is also the same pathfinding algorithm which was implemented by @cookt5 which I believe he said was based on Dijkstra's algorithm. Did you mean to implement a new pathfinding class, Jason? The PR doesn't include any changes to a PathFinding class like your PR comment says. Are you missing a file?

2023-03-28 02:28 UTC, closed without merging